export const SET_TRIP_TYPE = 'SET_TRIP_TYPE';
export const SET_SOURCE_CITY = 'SET_SOURCE_CITY';
export const SET_DESTINATION_CITY = 'SET_DESTINATION_CITY';
export const SET_DATE_OF_JOURNEY = 'SET_DATE_OF_JOURNEY';
export const BOOK_FLIGHT = 'BOOK_FLIGHT';
export const SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS';
